# Generated by Django 4.2 on 2023-04-09 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignment', '0001_initial'),
        ('quiz', '0002_alter_quizzes_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('hours', models.PositiveIntegerField(null=True)),
                ('assignments', models.ManyToManyField(to='assignment.assignment')),
                ('pages', models.ManyToManyField(to='page.page')),
                ('quizzes', models.ManyToManyField(to='quiz.quizzes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
